### ISSUE TITLE
Lower case nucleotides do not get any color

### ISSUE THREAD

**Issue by alejandrogzi** [moshi4/pyMSAviz#12]
Hi @moshi4 

Thanks for your useful tool. Just wanted to report this: 

If a .fa file has the nucleotides in lower case, no color is applied (with the exception of "Identity"):

![image](https://github.com/moshi4/pyMSAviz/assets/78838419/c427d673-f843-4c38-ae95-e15e097116a2)

On the other hand, if you convert them to upper case, color schemes work:

![image](https://github.com/moshi4/pyMSAviz/assets/78838419/9abb705a-dcf1-45f0-8739-11cdaad8105a)

I do not know if this is the desired functionality or a real bug (I personally think that they should be colored either way).

Best,
Alejandro

**Comment by moshi4** [comment]
Hi @alejandrogzi,

The default setting in pyMSAviz is no color for lowercase letters. If users want to set the color even for lowercase letters, it should be set explicitly with the `set_custom_color_scheme()` method.

e.g. `mv.set_custom_color_scheme(dict(a="lime", t="skyblue", g="salmon", c="orange"))`
