### ISSUE TITLE
Showing figure title

### ISSUE THREAD

**Issue by 0xorial** [moshi4/pyMSAviz#14]
If I try to add a title with .suptitle(), it does not render correctly:
<img width="440" alt="image" src="https://github.com/user-attachments/assets/cb2b937c-1bc2-430a-8e6b-6a38977dd1eb">

I narrowed it down to the call 
```
gs.update(left=0, right=1, bottom=0, top=1, hspace=0, wspace=0)
```

but I am not sure what could be done with it...

**Comment by moshi4** [comment]
Are you setting the y argument for `fig.suptitle()` method?

**Code Example**

```python
from pymsaviz import MsaViz, get_msa_testdata

msa_file = get_msa_testdata("HIGD2A.fa")
mv = MsaViz(msa_file, wrap_length=60, show_count=True)

fig = mv.plotfig()
fig.suptitle("pyMSAviz title", y=1.15, size=15, color="black")

fig.savefig("result.png")
```

**result.png**

![result](https://github.com/user-attachments/assets/49ed8d34-9831-4205-86f2-b2f16b54dd7d)

**Comment by 0xorial** [comment]
That solves the issue, thanks!
