### ISSUE TITLE
Possibly a way to put custom colors by "add_color" syntax rather than custom_color_func?

### ISSUE THREAD

**Issue by heejongkim** [moshi4/pyMSAviz#17]
Hi,

This is a very neat versatile tool that i've been looking for for awhile.

As I'm reading the API document and testing some example codes, I wonder if there's a add_color method just like add_marker but for coloring specific col, row position with hex or cmap. I would like to color individual position with different colors based on experimental values. It would be very easy to loop through if such method exists. 
Did I miss the information or a way to accomplish that somehow with the current version?
Thank you.

best,
heejong

**Comment by moshi4** [comment]
It seems to me that the `set_custom_color_func` method would accomplish your goal.
I'm not sure why you need to add a new method like add_color.

**Comment by heejongkim** [comment]
yeah you are right. I just thought that it may simplify my side workflow.
I made the dictionary of (row,col) = color to feed in set_custom_color_func.
Thanks.
