### ISSUE TITLE
matplotlib minimum version

### ISSUE THREAD

**Issue by tonytony99** [moshi4/pyMSAviz#7]
With matplotlib version 3.5.3 and pymsaviz version 0.4.0 installed, this example from the docs gave an AttributeError:

```python
from pymsaviz import MsaViz, get_msa_testdata

msa_file = get_msa_testdata("HIGD2A.fa")
mv = MsaViz(msa_file)
fig = mv.plotfig()
```
Extract from stack trace:
```python
... pymsaviz/msaviz.py) in plotfig(self, dpi) ...
--> 420         fig.set_layout_engine("tight")
    421         gs = GridSpec(nrows=len(plot_ax_types), ncols=1, height_ratios=y_size_list)
    422         gs.update(left=0, right=1, bottom=0, top=1, hspace=0, wspace=0)

AttributeError: 'Figure' object has no attribute 'set_layout_engine'
```
Installing matplotlib 3.6.0 fixed the issue so perhaps the minimum version (e.g. [matplotlib = ">=3.5.2" ](https://github.com/moshi4/pyMSAviz/blob/546869c4fe015c569e21a809964b0b209f3585d2/pyproject.toml#L35) ) may need updating?

**Comment by moshi4** [comment]
Hi @tonytony99,

Thank you for reporting the issue.

At the time of release, I test with the latest version of the dependent packages.
Therefore, as I develop and release more and more, I may not be able to support the minimum version previously available.

I will try to resolve this issue in the next release.
